POST http://localhost:8080/chat
Content-Type: application/json

{
  "message": "Hello"
}
###
GET http://localhost:8080/chat/history
###

GET http://localhost:8080/chat/999
###

PUT http://localhost:8080/chat/2
Content-Type: application/json

{
  "message": "How are you?"
}
###

DELETE http://localhost:8080/chat/4

