spring.application.name=ChatBot
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/chatbot_db
spring.datasource.username=postgres
spring.datasource.password=Ranju@7760$
spring.jpa.hibernate.ddl-auto=update